name: Build ikiwicc wiznote arm64 Full Image
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 允许写入ghcr容器仓库
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU multiarch
        uses: docker/setup-qemu-action@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.TOKEN }}

      - name: Build & Push to GHCR (完整arm64镜像)
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/arm64
          push: true # 推送到ghcr，不要load:true
          tags: ghcr.io/${{ github.repository_owner }}/wiznote:arm64

      - name: Pull full arm64 image
        run: docker pull ghcr.io/${{ github.repository_owner }}/wiznote:arm64

      - name: Export full image to tar.gz
        run: |
          docker save ghcr.io/${{ github.repository_owner }}/wiznote:arm64 | gzip > wiznote-ikiwicc-full-arm64.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wiznote-ikiwicc-full-arm64
          path: wiznote-ikiwicc-full-arm64.tar.gz
